### ISSUE TITLE
PPO RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0

### ISSUE THREAD

**Issue by leckylao** [smearle/gym-city#10]
Hi Sam,

I have A2C and ACKTR running fine but when running PPO I am having the following error. Any ideas?

```
Traceback (most recent call last):
  File "train.py", line 569, in <module>
    main()
  File "train.py", line 27, in main
    trainer.main()
  File "train.py", line 317, in main
    self.train()
  File "train.py", line 440, in train
    value_loss, action_loss, dist_entropy = agent.update(rollouts)
  File "/home/lecky/Workspaces/gym-city/algo/ppo.py", line 35, in update
    advantages = rollouts.returns[:-1] - rollouts.value_preds[:-1]
RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0
```

**Comment by smearle** [comment]
Great news! I've never run it using PPO. But clearly, the size of "value_preds" and "returns" do not match. Try printing out the shapes of these tensors and modify the neural network as necessary so that they match.
